<?php
/**
 * Created by PhpStorm.
 * User: 南丞
 * Date: 2019/3/8
 * Time: 11:03
 *
 *
 *                      _ooOoo_
 *                     o8888888o
 *                     88" . "88
 *                     (| ^_^ |)
 *                     O\  =  /O
 *                  ____/`---'\____
 *                .'  \\|     |//  `.
 *               /  \\|||  :  |||//  \
 *              /  _||||| -:- |||||-  \
 *              |   | \\\  -  /// |   |
 *              | \_|  ''\---/''  |   |
 *              \  .-\__  `-`  ___/-. /
 *            ___`. .'  /--.--\  `. . ___
 *          ."" '<  `.___\_<|>_/___.'  >'"".
 *        | | :  `- \`.;`\ _ /`;.`/ - ` : | |
 *        \  \ `-.   \_ __\ /__ _/   .-` /  /
 *  ========`-.____`-.___\_____/___.-`____.-'========
 *                       `=---='
 *  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 *           佛祖保佑       永无BUG     永不修改
 *
 */

class BaseTest extends \PHPUnit\Framework\TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        \pf\config\Config::loadFiles('tests/config');
    }

    public function testWeb()
    {
        $this->assertTrue(\pf\middleware\Middleware::web('auth'));
    }
}